language: cpp
sudo: required
dist: trusty
cache: apt

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-5
      - clang-3.8

compiler:
  - g++-5
  - clang-3.8

os:
  - linux
  # - osx

before_install:
  - uname -a
  - wget https://cmake.org/files/v3.5/cmake-3.5.1.tar.gz
  - tar xf cmake-3.5.1.tar.gz
  - cd cmake-3.5.1
  - ./configure
  - make
  - cd ..

script:
  - echo "data_file data" > tester/tester.conf
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd tester
  - dd if=/dev/urandom of=./data bs=8M count=4
  - ./tester

notifications:
  email: false