cache: apt
dist: trusty
language: cpp
sudo: required

addons:
  apt:
    packages:
      - g++-5
      - clang-3.8
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8

matrix:
  include:
    - os: linux
      env: CXX=g++-5 CC=gcc-5
    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8

# installing cmake 3.5
# before_install:
#   - wget https://cmake.org/files/v3.5/cmake-3.5.1.tar.gz
#   - tar xf cmake-3.5.1.tar.gz
#   - cd cmake-3.5.1
#   - ./configure
#   - make
#   - cd ..

script:
  - echo "data_file data" > tester/tester.conf
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd tester
  - dd if=/dev/urandom of=./data bs=8M count=4
  - ./tester

notifications:
  email: false
